## Random numbers

In [52]:
import random as rnd
import numpy as np

In [53]:
rnd.random()

0.8375779756625729

In [54]:
rnd.seed(1)
rnd.random()

0.13436424411240122

In [55]:
rnd.randint(0, 10)

1

In [56]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
rnd.choice(x)

5

In [57]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
rnd.shuffle(x)
print(x)

[9, 3, 1, 5, 6, 4, 7, 8, 2]


## zufällige Matrizen

In [63]:
np.random.rand(3, 4)

array([[0.9383686 , 0.88903422, 0.69124851, 0.75638918],
       [0.26019726, 0.06942184, 0.21283089, 0.1366328 ],
       [0.19386296, 0.9215378 , 0.80017705, 0.17042012]])

In [64]:
np.round(np.random.rand(3,4))

array([[0., 1., 1., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.]])

In [67]:
np.random.randint(10, 100, size=(4, 10))

array([[11, 76, 61, 88, 99, 49, 75, 92, 11, 87],
       [19, 50, 25, 75, 74, 80, 22, 49, 35, 13],
       [40, 47, 16, 68, 95, 99, 23, 31, 78, 94],
       [67, 83, 83, 36, 66, 17, 99, 39, 69, 61]])

## Spezielle Verteilungen

In [79]:
a,b = 5, 10
rnd.uniform(a, b)

6.587148160881921

In [82]:
np.random.uniform(a, b, size=(3, 5))

array([[5.34277834, 5.62409688, 7.1257128 , 5.96815295, 5.16970623],
       [6.95001251, 8.68169002, 9.87310962, 5.26381477, 9.61051253],
       [5.78046589, 8.49763922, 8.5656909 , 9.91170065, 6.08707784]])

In [101]:
lmbda = 10
rnd.expovariate(lmbda)

0.11296341487934962

In [103]:
np.random.exponential(lmbda, size=(3, 5))

array([[10.15794476,  5.5449078 , 49.53679557,  0.15462463,  5.22530568],
       [ 6.10900679,  7.98612497,  2.54923678,  8.09821767,  2.52607188],
       [ 4.71454014, 19.94247369, 51.65053844, 12.26028206,  6.30432118]])

In [110]:
mu, sgm = 50, 5
rnd.gauss(mu, sgm)

55.699128351817116

In [111]:
np.random.normal(mu, sgm, size=(3, 5))

array([[48.41370116, 45.52105806, 54.24712719, 46.53159809, 48.37629997],
       [58.34387338, 47.15351353, 53.0351053 , 51.72718067, 49.42556083],
       [47.51191433, 41.90816065, 51.69213427, 47.91585478, 56.57371948]])

In [112]:
n,p = 50, 0.3
np.random.binomial(n,p,size=(4,10))

array([[19, 13, 17, 20, 14, 11, 16, 11, 11, 15],
       [17, 16, 20, 15, 14, 19, 13, 12, 23, 17],
       [14, 14, 17, 19, 16, 14, 15, 13, 14, 18],
       [15, 10, 21, 15, 16,  8, 18, 15, 14, 14]])

In [113]:
p = 0.2
np.random.geometric(p, size=(4,8))

array([[ 1,  5,  3,  6,  2,  7,  4,  7],
       [ 7,  3, 12,  2,  2,  1,  5,  4],
       [14,  1,  1,  3,  2,  5,  3,  1],
       [ 1,  4,  4,  5,  6, 10,  3,  6]])

## Reproduzierbarkeit

In [114]:
np.random.seed(1)
np.random.normal(10, 1, size=(2,4))

array([[11.62434536,  9.38824359,  9.47182825,  8.92703138],
       [10.86540763,  7.6984613 , 11.74481176,  9.2387931 ]])