# Markov-Ketten

## Diskrete Markov-Ketten

In [1]:
import numpy as np

def m_te_uebergangsmatrix(uebergangsmatrix, m):
    # m beschreibt die Anzahl der Schritte (= Potenz der Matrix)
    result = uebergangsmatrix
    for k in range(m - 1):
        result = np.matmul(result, uebergangsmatrix)
    return result

### Für Aufgabe 2 genutzt

In [50]:
# pi_0 = np.array([1/28, 7/28, 16/28, 2/28, 2/28, 0/28])
pi_0 = np.array([0, 0, 0, 0, 1, 0])

uebergangsmatrix = np.array([
    [0.65, 0.21, 0.14, 0, 0, 0],
    [0.17, 0.5, 0.2, 0.11, 0.02, 0],
    [0.09, 0.25, 0.27, 0.24, 0.14, 0.01],
    [0, 0.11, 0.19, 0.4, 0.21, 0.09],
    [0, 0.0, 0.09, 0.23, 0.47, 0.21],
    [0, 0, 0.01, 0.12, 0.21, 0.66]
])

alpha = 1e-3
# Absichern, dass der Ausgangsvektor Sinn macht
assert 1-alpha <= sum(pi_0) <= 1+alpha, f"Die Summe von pi_0 ist mit {sum(pi_0)} im Bereich von [{1-alpha}, {1+alpha}]"

# Einfach zum Absichern, dass ich nicht in der Zeile verrutscht bin
for index, row in enumerate(uebergangsmatrix):
    assert 1-alpha <= sum(row) <= 1+alpha, f"Die Summe der Zeile {index + 1} ist mit {sum(row)} im Bereich von [{1-alpha}, {1+alpha}]"

result = np.matmul(pi_0, m_te_uebergangsmatrix(uebergangsmatrix, m=2))
# result = m_te_uebergangsmatrix(uebergangsmatrix, m=5)
print(result)

[0.0081 0.0478 0.1124 0.2469 0.3259 0.2589]


### Für Aufgabe 3 genutzt

In [52]:
pi_0 = np.array([1/4, 1/4, 1/4, 1/4])

uebergangsmatrix = np.array([
    [0, 1/3, 1/3, 1/3],
    [0, 0, 0, 1],
    [1/3, 1/3, 0, 1/3],
    [1, 0, 0, 0]
])

alpha = 1e-3
# Absichern, dass der Ausgangsvektor Sinn macht
assert 1-alpha <= sum(pi_0) <= 1+alpha, f"Die Summe von pi_0 ist mit {sum(pi_0)} im Bereich von [{1-alpha}, {1+alpha}]"

# Einfach zum Absichern, dass ich nicht in der Zeile verrutscht bin
for index, row in enumerate(uebergangsmatrix):
    assert 1-alpha <= sum(row) <= 1+alpha, f"Die Summe der Zeile {index + 1} ist mit {sum(row)} im Bereich von [{1-alpha}, {1+alpha}]"

result = np.matmul(pi_0, m_te_uebergangsmatrix(uebergangsmatrix, m=100000))
# result = m_te_uebergangsmatrix(uebergangsmatrix, m=5)
print(result)

[0.375      0.16666667 0.125      0.33333333]


## Stetige Markov-Ketten

In [114]:
import numpy as np
from sympy import Symbol, symbols, Eq, solve

intensitaetsmatrix = np.array([
    [-3/7, 1/7, 2/7, 0],
    [0, -4/14, 1/14, 3/14],
    [4/19, 0, -5/19, 1/19],
    [0, 4/11, 4/11, -8/11]
])

# intensitaetsmatrix = np.array([
#     [-1/2, 0, 1/2],
#     [1/20, -3/10, 1/4],
#     [1/10, 2/9, -29/90]
# ])

# Überprüfe, dass die Intensitätsmatrix Sinn macht -> Zeilensummen müssen 0 sein
alpha = 1e-3
for index, row in enumerate(intensitaetsmatrix):
    assert -alpha <= sum(row) <= alpha, f"Die Zeilensumme der Intensitätsmatrix ist in der Zeile {index + 1} mit {sum(row)} nicht im Intervall [{-alpha}, {alpha}]"

def get_stationary(intensity_matrix):
    a, b, c, d = symbols('a b c d')
    equations = []
    
    # Matrix transponieren, damit ich über die Spalten laufen kann
    _ = np.transpose(intensity_matrix)
    for row in _:
        print(row)
        equations.append(Eq(row[0] * a + row[1] * b + row[2] * c + row[3] * d, 0))
    # Hinzufügen der Nebenbedingung
    equations.append(Eq(a + b + c + d, 1))
    # Sympy errechnet die Lösung des Gleichungssystems
    return solve(equations)

x = get_stationary(intensitaetsmatrix)
print(x)

[-0.42857143  0.          0.21052632  0.        ]
[ 0.14285714 -0.28571429  0.          0.36363636]
[ 0.28571429  0.07142857 -0.26315789  0.36363636]
[ 0.          0.21428571  0.05263158 -0.72727273]
{a: 0.217054263565891, b: 0.238759689922481, c: 0.441860465116279, d: 0.102325581395349}
